apiVersion: batch/v1
kind: Job
metadata:
  name: upload-gpu-script
  namespace: smartshop
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 0
      containers:
        - name: uploader
          image: quay.io/abdhumal/smartshop-spark-jobs-rapids:latest
          securityContext:
            runAsUser: 0
          command: [sh, -c]
          args:
            - |
              export MC_CONFIG_DIR=/tmp/.mc
              mkdir -p /tmp/.mc
              curl -fsSL -o /usr/local/bin/mc \
                https://dl.min.io/client/mc/release/linux-amd64/mc
              chmod +x /usr/local/bin/mc
              mc alias set minio http://minio.smartshop.svc.cluster.local:9000 \
                "${AWS_ACCESS_KEY_ID}" "${AWS_SECRET_ACCESS_KEY}"
              mc cp /opt/spark/getGpusResources.sh \
                minio/smartshop-raw/jars/getGpusResources.sh
              mc anonymous set download minio/smartshop-raw/jars
              echo "Done"
              mc ls minio/smartshop-raw/jars/
          envFrom:
            - secretRef:
                name: smartshop-credentials
