apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: smartshop-rapids-1exec
  namespace: smartshop
spec:
  type: Python
  mode: cluster
  pythonVersion: "3"
  image: "quay.io/abdhumal/smartshop-spark-jobs-rapids:latest"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/feature_engineering.py"
  arguments:
    - "--input"
    - "s3a://smartshop-raw/raw/reviews/"
    - "--output"
    - "s3a://smartshop-features/rapids-1exec-test/"
  sparkVersion: "3.5.3"
  restartPolicy:
    type: Never
  hadoopConf:
    fs.s3a.endpoint: "http://minio.smartshop.svc.cluster.local:9000"
    fs.s3a.path.style.access: "true"
    fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    fs.s3a.aws.credentials.provider: "com.amazonaws.auth.EnvironmentVariableCredentialsProvider"
  sparkConf:
    spark.plugins: "com.nvidia.spark.SQLPlugin"
    spark.rapids.sql.enabled: "true"
    spark.rapids.sql.concurrentGpuTasks: "2"
    spark.rapids.memory.pinnedPool.size: "2g"
    spark.executor.memoryOverhead: "3g"
    spark.executor.resource.gpu.amount: "1"
    spark.executor.resource.gpu.vendor: "nvidia.com"
    spark.task.resource.gpu.amount: "0.5"
    spark.executor.resource.gpu.discoveryScript: "/opt/spark/getGpusResources.sh"
    spark.jars: "http://minio.smartshop.svc.cluster.local:9000/smartshop-raw/jars/hadoop-aws-3.3.4.jar,http://minio.smartshop.svc.cluster.local:9000/smartshop-raw/jars/aws-java-sdk-bundle-1.12.262.jar,http://minio.smartshop.svc.cluster.local:9000/smartshop-raw/jars/rapids-4-spark-cuda13.jar"
    spark.sql.adaptive.enabled: "true"
    # Disable GPU memory pool to avoid allocation failures on first run
    spark.rapids.memory.gpu.pooling.enabled: "false"
  driver:
    cores: 2
    memory: "4g"
    serviceAccount: spark
    javaOptions: "-Duser.dir=/tmp"
    envFrom:
      - secretRef:
          name: smartshop-credentials
    volumeMounts:
      - name: feature-engineering-script
        mountPath: /opt/spark/work-dir/feature_engineering.py
        subPath: feature_engineering.py
  executor:
    cores: 4
    instances: 1
    memory: "8g"
    javaOptions: "-Duser.dir=/tmp"
    gpu:
      name: "nvidia.com/gpu"
      quantity: 1
    envFrom:
      - secretRef:
          name: smartshop-credentials
    volumeMounts:
      - name: feature-engineering-script
        mountPath: /opt/spark/work-dir/feature_engineering.py
        subPath: feature_engineering.py
  volumes:
    - name: feature-engineering-script
      configMap:
        name: smartshop-feature-engineering-script
        defaultMode: 0644
